-- ============================================================
-- Lab Q21: Student Records Database
-- Run this FIRST in phpMyAdmin before opening the website
-- ============================================================

-- Step 1: Create the database
CREATE DATABASE IF NOT EXISTS student_db
    CHARACTER SET utf8mb4        -- Supports all characters including emojis
    COLLATE utf8mb4_unicode_ci;  -- Case-insensitive comparisons

-- Step 2: Use this database
USE student_db;

-- Step 3: Create the students table
-- This table stores ALL student information
CREATE TABLE IF NOT EXISTS students (

    -- PRIMARY KEY: unique ID auto-generated by MySQL (1, 2, 3, ...)
    id          INT             AUTO_INCREMENT PRIMARY KEY,

    -- Student's full name — cannot be empty (NOT NULL)
    name        VARCHAR(100)    NOT NULL,

    -- Roll number — unique so no two students have same roll no
    roll_no     VARCHAR(20)     NOT NULL UNIQUE,

    -- Email address — must be unique across all students
    email       VARCHAR(150)    NOT NULL UNIQUE,

    -- Department as a fixed set of options (ENUM)
    department  ENUM(
                    'Computer Science',
                    'Information Technology',
                    'Electronics',
                    'Mechanical',
                    'Civil',
                    'Electrical'
                ) NOT NULL,

    -- Year of study: 1st, 2nd, 3rd, or 4th year
    year        TINYINT         NOT NULL CHECK (year BETWEEN 1 AND 4),

    -- CGPA: e.g. 8.75 (5 digits total, 2 after decimal)
    cgpa        DECIMAL(4,2)    DEFAULT 0.00 CHECK (cgpa BETWEEN 0 AND 10),

    -- Phone number stored as string (to allow leading zeros, country codes)
    phone       VARCHAR(15)     DEFAULT NULL,

    -- Timestamp: automatically set to NOW() when record is created
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,

    -- Timestamp: automatically updated every time record is modified
    updated_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ============================================================
-- Step 4: Insert sample/seed data for testing
-- ============================================================
INSERT INTO students (name, roll_no, email, department, year, cgpa, phone) VALUES
('Alice Patel',      'CS001', 'alice@college.edu',   'Computer Science',        3, 8.75, '9876543210'),
('Bob Kulkarni',     'CS002', 'bob@college.edu',     'Computer Science',        2, 7.50, '9876543211'),
('Carol Mehta',      'IT001', 'carol@college.edu',   'Information Technology',  4, 9.10, '9876543212'),
('David Sharma',     'EC001', 'david@college.edu',   'Electronics',             1, 6.80, '9876543213'),
('Eva Joshi',        'ME001', 'eva@college.edu',     'Mechanical',              3, 7.25, '9876543214'),
('Frank Singh',      'CS003', 'frank@college.edu',   'Computer Science',        4, 8.90, '9876543215'),
('Grace Verma',      'IT002', 'grace@college.edu',   'Information Technology',  2, 9.50, '9876543216'),
('Henry Desai',      'CV001', 'henry@college.edu',   'Civil',                   1, 7.00, '9876543217'),
('Iris Nair',        'EL001', 'iris@college.edu',    'Electrical',              3, 8.30, NULL),
('Jay Reddy',        'CS004', 'jay@college.edu',     'Computer Science',        2, 6.50, '9876543219');

-- Verify the data was inserted correctly
SELECT * FROM students ORDER BY roll_no;
