-- ============================================================
-- FILE: setup.sql
-- PURPOSE: Creates the database and all tables with sample data
-- HOW TO RUN: Open phpMyAdmin → SQL tab → Paste this → Click Go
-- ============================================================

-- Step 1: Create the database
CREATE DATABASE IF NOT EXISTS waste_management;

-- Step 2: Switch to that database
USE waste_management;

-- ---- TABLE 1: waste_reports ----
-- Stores every citizen waste complaint
CREATE TABLE IF NOT EXISTS waste_reports (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    -- AUTO_INCREMENT: each row gets next number automatically (1,2,3...)
    -- PRIMARY KEY: uniquely identifies each report

    reporter_name  VARCHAR(100) NOT NULL,   -- Who is reporting
    reporter_phone VARCHAR(15)  NOT NULL,   -- Contact phone
    reporter_email VARCHAR(100) DEFAULT NULL, -- Optional email

    waste_type     VARCHAR(50)  NOT NULL,
    -- Plastic, Paper, Organic, Electronic, Chemical, Mixed

    location       VARCHAR(255) NOT NULL,   -- Address of the waste
    landmark       VARCHAR(150) DEFAULT NULL, -- Nearby landmark
    city           VARCHAR(100) NOT NULL,   -- City/area

    quantity       ENUM('Small','Medium','Large','Very Large') DEFAULT 'Medium',
    -- ENUM: column that only allows specific predefined values
    -- Small=bags, Medium=bin-size, Large=truck, Very Large=multiple trucks

    description    TEXT         DEFAULT NULL, -- Extra details
    
    status ENUM('Pending','Assigned','In Progress','Collected','Closed') DEFAULT 'Pending',
    -- Lifecycle: Pending → Assigned → In Progress → Collected → Closed

    priority       ENUM('Low','Normal','High','Urgent') DEFAULT 'Normal',
    assigned_to    VARCHAR(100) DEFAULT NULL, -- Authority team name
    admin_notes    TEXT         DEFAULT NULL, -- Admin instructions
    
    reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- TIMESTAMP DEFAULT CURRENT_TIMESTAMP: auto-records when row was inserted

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    -- ON UPDATE CURRENT_TIMESTAMP: auto-updates timestamp whenever row changes
);

-- ---- TABLE 2: authorities ----
-- Waste collection teams/authorities in the system
CREATE TABLE IF NOT EXISTS authorities (
    id        INT AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(100) NOT NULL,  -- Team name
    area      VARCHAR(100) NOT NULL,  -- Zone/city they cover
    phone     VARCHAR(15)  NOT NULL,  -- Contact number
    email     VARCHAR(100) DEFAULT NULL,
    vehicle   VARCHAR(50)  DEFAULT NULL, -- Type of vehicle
    is_active TINYINT(1)   DEFAULT 1    -- 1=active, 0=inactive (boolean)
);

-- ---- TABLE 3: admins ----
-- Admin login credentials
CREATE TABLE IF NOT EXISTS admins (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE, -- Must be unique across all admins
    password VARCHAR(255) NOT NULL,        -- Stored as bcrypt hash (never plain text!)
    fullname VARCHAR(100) NOT NULL
);

-- ============================================================
-- SEED DATA: Insert sample data for demo
-- ============================================================

-- Default admin: username=admin, password=admin123
-- Hash generated by: password_hash('admin123', PASSWORD_DEFAULT)
INSERT INTO admins (username, password, fullname) VALUES
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'System Administrator');

-- Waste collection authorities
INSERT INTO authorities (name, area, phone, email, vehicle) VALUES
('Green Team Alpha',   'Pune - Zone A',  '9876543210', 'alpha@municipal.gov',  'Compactor Truck'),
('Clean Squad Beta',   'Pune - Zone B',  '9876543211', 'beta@municipal.gov',   'Pick-up Van'),
('EcoForce Gamma',    'Mumbai Central', '9876543212', 'gamma@municipal.gov',   'Tractor Trolley'),
('SwachhDal Delta',   'Mumbai West',    '9876543213', 'delta@municipal.gov',   'Compactor Truck'),
('CleanCity Epsilon', 'Nashik',         '9876543214', 'epsilon@municipal.gov', 'Pick-up Van');

-- Sample waste reports for demo
INSERT INTO waste_reports
  (reporter_name, reporter_phone, waste_type, location, landmark, city, quantity, description, status, priority, assigned_to)
VALUES
('Rahul Sharma', '9000000001', 'Plastic',    'Near Bus Stop, MG Road',     'Opposite SBI Bank',    'Pune',   'Large',      'Large pile of plastic bags and bottles.', 'Assigned',    'High',   'Green Team Alpha'),
('Priya Patel',  '9000000002', 'Paper',      'Gandhi Nagar, Lane 4',       'Next to School Gate',  'Pune',   'Medium',     'Old newspapers and cardboard on footpath.','In Progress', 'Normal', 'Clean Squad Beta'),
('Amit Kumar',   '9000000003', 'Mixed',      'Shivaji Market, Main Gate',  'Market Entrance',      'Mumbai', 'Very Large', 'Overflowing market waste — multiple types.','Pending',    'Urgent', NULL),
('Sunita Devi',  '9000000004', 'Electronic', 'IT Park Road, Building 7',   'Near Security Cabin',  'Pune',   'Small',      'Old computers and wires near parking.',   'Pending',     'Normal', NULL),
('Raj Mehta',    '9000000005', 'Organic',    'Vegetable Market, Block B',  'Behind Main Stalls',   'Nashik', 'Large',      'Rotting vegetables, bad smell.',          'Collected',   'High',   'CleanCity Epsilon');
